### ISSUE TITLE
app crashes since update v0.5+

### ISSUE THREAD

**Issue by sljtre** [LiamAbyss/Scorpion#17]
Since version 5, the application crashes when the new "info" icon on a course is pressed

The problem happens when opening scorpion for the first time. Once the application has crashed, it closes at each new attempt to start.
To open it again, I have to delete all the data from the application (and reconnect) but the problem still occurs.

Smartphone :
 - Device: POCO f1 (Xiaomi)
 - OS: MIUI 11.0.9 (Android 10)

Do you think you could look at the problem to solve it?

Thanks for the development of this app which is really more convenient than Aurion! I see new updates regularly this month, it's great!

**Comment by LiamAbyss** [comment]
Hi @sljtre, thanks for the feedback !
I can see why the app would crash when ⓘ is pressed (and this will be fixed in the next update), but I can't understand why the app wouldn't start after that.
It is possible that this problem is related to **Aurion**. As we only have access to our own planning, we can't test some weird scenarios that **Aurion** sends back to us (wouldn't be the first time, won't be the last).

The easiest way for us to solve this problem would be to meet at ISEN. Do you have some time tomorrow in the afternoon ?

**Comment by sljtre** [comment]
Sure ! I'm available this afternoon from 14:00 when you prefer

**Comment by LiamAbyss** [comment]
Nice ! I'll be in C404 at 14:00, see you then !
